/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "Site": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "VideoProcessing": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VideoProcessingDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VideoPublisher": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
